"""Backend protocols, shipped implementations, and the selection registry."""

from .base import (
    TASKS,
    Backend,
    BackendError,
    BackendUnavailable,
    Embeddings,
    EmbedBackend,
    ImageEmbedBackend,
    OCRBackend,
    OCRItem,
    STTBackend,
    Segment,
    Transcription,
    Word,
)
from .registry import (
    EMBED_BACKENDS,
    IMAGE_EMBED_BACKENDS,
    OCR_BACKENDS,
    STT_BACKENDS,
    UnknownBackend,
    available,
    build_backend,
    build_backends,
)

__all__ = [
    "TASKS",
    "Backend",
    "BackendError",
    "BackendUnavailable",
    "EmbedBackend",
    "Embeddings",
    "ImageEmbedBackend",
    "OCRBackend",
    "OCRItem",
    "STTBackend",
    "Segment",
    "Transcription",
    "Word",
    "EMBED_BACKENDS",
    "IMAGE_EMBED_BACKENDS",
    "OCR_BACKENDS",
    "STT_BACKENDS",
    "UnknownBackend",
    "available",
    "build_backend",
    "build_backends",
]
