// Emits src/styles/tokens.css and src/styles/type.css from the YAML frontmatter
// of ../DESIGN.md, which is the design system's single source of truth.
//
//   pnpm tokens          rewrite both files
//   pnpm tokens:check    exit 1 if either file is stale (CI, pre-commit)
//
// A `{colors.gold}` reference becomes `var(--gold)` rather than the literal
// hex, so an alias stays an alias in the emitted CSS: the six pinned role names
// (`--bg`, `--accent`, ...) carry no value of their own, exactly as DESIGN.md
// says they must.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const here = dirname(fileURLToPath(import.meta.url));
const DESIGN_MD = resolve(here, "../../DESIGN.md");
const OUT_DIR = resolve(here, "../src/styles");
const HEADER = `/* GENERATED by web/scripts/tokens.mjs from DESIGN.md. Do not edit;
   change the frontmatter and run \`pnpm tokens\`. */\n`;

function frontmatter(markdown) {
  const match = /^---\n([\s\S]*?)\n---\n/.exec(markdown);
  if (!match) throw new Error(`${DESIGN_MD}: no YAML frontmatter`);
  return parse(match[1]);
}

// Groups emitted as custom properties, and the prefix each name gets. Colours,
// spacing, layout, elevation and motion are unprefixed on purpose: the three
// Python-served stylesheets already use `--gold`, `--s4`, `--gut`, `--drop`,
// and one vocabulary across four surfaces is the point.
const GROUPS = [
  ["colors", ""],
  ["spacing", ""],
  ["layout", ""],
  ["elevation", ""],
  ["motion", ""],
  ["film", "film-"],
  ["weights", "w-"],
];

// `{colors.gold}` -> `var(--gold)`; anything unknown is an error rather than a
// silent literal.
function deref(value) {
  if (typeof value !== "string") return String(value);
  return value.replace(/\{([^}]+)\}/g, (_, path) => {
    const [group, ...rest] = path.split(".");
    const prefix = Object.fromEntries(GROUPS)[group];
    if (prefix !== undefined) return `var(--${prefix}${rest.join(".")})`;
    if (group === "rounded") return "0";
    throw new Error(`unresolvable token reference {${path}}`);
  });
}

// A role's font-family may be a literal stack or `{typography.other.fontFamily}`;
// follow the chain to the literal.
function familyOf(design, role) {
  const value = design.typography[role].fontFamily;
  const ref = /^\{typography\.([^.]+)\.fontFamily\}$/.exec(value);
  return ref ? familyOf(design, ref[1]) : value;
}

function tokensCss(design) {
  const lines = [HEADER, ":root {", "  color-scheme: dark;", ""];
  const seen = new Set();
  const emit = (name, value) => {
    if (seen.has(name)) throw new Error(`duplicate token --${name}`);
    seen.add(name);
    lines.push(`  --${name}: ${value};`);
  };
  for (const [group, prefix] of GROUPS) {
    lines.push(`  /* ${group} */`);
    for (const [key, value] of Object.entries(design[group])) {
      emit(`${prefix}${key}`, deref(value));
    }
    lines.push("");
  }
  // `--sans` and `--mono` are deliberately not emitted: next/font names the
  // loaded faces itself, so app/globals.css binds the two aliases to the
  // font loader's variables. type.css only ever refers to the aliases.
  lines.push("}", "");
  return lines.join("\n");
}

// One global class per typography role. A CSS Module opts in with
// `composes: t-body from global;` so the role name stays readable in markup.
function typeCss(design) {
  const sans = familyOf(design, "body");
  const mono = familyOf(design, "machine");
  const family = (role) => {
    const literal = familyOf(design, role);
    if (literal === sans) return "var(--sans)";
    if (literal === mono) return "var(--mono)";
    throw new Error(`typography.${role} uses a third face: ${literal}`);
  };
  const lines = [HEADER];
  for (const [role, spec] of Object.entries(design.typography)) {
    lines.push(`.t-${role} {`);
    lines.push(`  font-family: ${family(role)};`);
    lines.push(`  font-size: ${spec.fontSize};`);
    lines.push(`  font-weight: ${spec.fontWeight};`);
    lines.push(`  line-height: ${spec.lineHeight};`);
    lines.push(`  letter-spacing: ${spec.letterSpacing};`);
    if (spec.textTransform) lines.push(`  text-transform: ${spec.textTransform};`);
    const features = String(spec.fontFeature ?? "");
    if (features.includes("tabular-nums")) lines.push("  font-variant-numeric: tabular-nums;");
    if (features.includes("ligatures none")) lines.push("  font-variant-ligatures: none;");
    lines.push("}", "");
  }
  return lines.join("\n");
}

const design = frontmatter(readFileSync(DESIGN_MD, "utf8"));
const outputs = {
  "tokens.css": tokensCss(design),
  "type.css": typeCss(design),
};

if (process.argv.includes("--check")) {
  let stale = false;
  for (const [file, want] of Object.entries(outputs)) {
    let have = "";
    try {
      have = readFileSync(resolve(OUT_DIR, file), "utf8");
    } catch {
      /* missing counts as stale */
    }
    if (have !== want) {
      stale = true;
      console.error(`src/styles/${file} is stale: run \`pnpm tokens\``);
    }
  }
  process.exit(stale ? 1 : 0);
}

mkdirSync(OUT_DIR, { recursive: true });
for (const [file, text] of Object.entries(outputs)) {
  writeFileSync(resolve(OUT_DIR, file), text);
  console.log(`wrote src/styles/${file}`);
}
